### ISSUE TITLE
Add support for TSQL analysis in standalone mode

### ISSUE THREAD

**Issue by duncanp-sonar** [SonarSource/sonarlint-visualstudio#1003]
### Description

Support TSQL as an additional language in standalone mode.

### Sub-tasks

- [ ] include the SonarTSQL plugin in the daemon
- [ ] modify IDaemonAnalyzer to handle TSQL files
- [ ] update telemetry
- [ ] update documentation
- [ ] update the UI to refer to TSQL
- [ ] rule configuration in standalone mode ??? (perhaps not in the first iteration; see related tickets about adding standalone config for C/C++ and standalone config for VSCode)

**Comment by qrider** [comment]
Is this still on the roadmap?

**Comment by duncanp-sonar** [comment]
@qrider it's not on the roadmap for 2020, I'm afraid.

**Comment by gayanper** [comment]
Any update on this ? Adding this support will benefit since we can use vscode as a light weight database tool by install some azure studio db extensions.

**Comment by duncanp-sonar** [comment]
Closing as obsolete. Support for TSQL in standalone and Connected Mode is on the product backlog, but will be implemented differently (the daemon referred to above was dropped several years ago).
We'll create new implementation tickets when we start working on the MMF.
