### ISSUE TITLE
Support disabling C++ rules in standalone mode

### ISSUE THREAD

**Issue by duncanp-sonar** [SonarSource/sonarlint-visualstudio#1015]
Related MMF: [MMF-1833: Developer should be able deactivate C/C++ rules in SonarLint for VS](https://jira.sonarsource.com/browse/MMF-1833)

Sub-tasks:

- [x] #1016: Apply the user-level C++ rules configuration during analysis
- [x] #1017: Re-analyse C++ files when the user-level rules configuration changes
- [x] #1018: Add UI command to deactivate a specific C++ rule
- [x] #1019: Add UI command to open the user-level configuration file
- [x] #1020: Update documentation to describe user-level rules configuration

**Additional context**
Related ticket: #771

### Testing

Matrix: VS2015, VS2017, VS2019

Test cases:
- [x] `settings.json` does not exist; disable CFamily rule
   -> file created
   -> re-analysis of open files triggered, issues removed for Error List

- [x] manually edit `settings.json` to be invalid json, save -> no error, warning in output window that default rules used

- [x] manually edit and save `settings.json` -> re-analysis triggered

- [x] manually edit and save `settings.json`, then save again quickly
     -> first re-analysis triggered
     -> first re-analysis cancelled, new re-analysis triggered

- [x] attempt to disable SonarLint JavaScript rule -> disable rule context menu item does not appear

- [x] attempt to disable non-SonarLint rule -> disable rule context menu item does not appear

**Comment by jmlundberg** [comment]
Hi. Thank you for adding the settings.json mechanism.
Apologies for asking this here - There's already too many closed issues to what I'm suggesting/asking.

Is it possible with current mechanisms to completely disable C++ scanning, or all rules? (visual studio/windows)

We use other checkers for C++ but depend on sonarlint for C#. Is there a workaround to disable C++ sonarlint scanning completely? Even a hack is acceptable.

I propose a similar design as other similar tools take these days: scan for a settings file from the files directories and in parent directories. (eg how visual studio and resharper finds and reads .editorconfig)

Combined with an option to turn off c++ scanning completely in the .json.

I posted a question here but got no response - 
https://community.sonarsource.com/t/visual-studio-disable-all-c-inspections-in-a-repo-directory-or-solution/17593

**Comment by duncanp-sonar** [comment]
Hi @jmlundberg. Apologies, I missed your forum post. I'll reply there as that will be more visible to the community.

**Comment by jmlundberg** [comment]
@duncanp-sonar I added another comment. https://community.sonarsource.com/t/visual-studio-disable-all-c-inspections-in-a-repo-directory-or-solution/17593/3

**Comment by jmlundberg** [comment]
Hi @duncanp-sonar, we are still suffering from this issue and more than ever. Note my forum comment a few days ago:
https://community.sonarsource.com/t/visual-studio-disable-all-c-inspections-in-a-repo-directory-or-solution/17593/4

I've seen that there are several bugs connected to this item, perhaps there's new developments?

**Comment by jmlundberg** [comment]
@rita-g-sonarsource @duncanp-sonar 
Here's a simplistic tweak to CLangAnalyzer.cs that _does it_, namely disables C++ scanning unless the string "SonarLintCppEnable" is found in SonarLint.xml of the files directory or any parent.

Surely not a PR, but could be useful for others who need sonarlint for eg C# but don't need C++ or C scanning and who suffer multiple analysers scanning C++ or C files both in terms of scan times and confusing non-configured warnings. Clearly the configuration should be picked up by proper means, not like this, but I couldn't figure out where and how to implement that. 

`        public void ExecuteAnalysis(string path,
            IEnumerable<AnalysisLanguage> detectedLanguages,
            IIssueConsumer consumer,
            IAnalyzerOptions analyzerOptions,
            IAnalysisStatusNotifier statusNotifier,
            CancellationToken cancellationToken)
        {
            try{
                var dirname = Path.GetDirectoryName(path);
                String oldDirName = "";
                int maxdepth = 50;
                while (oldDirName != dirname && maxdepth>=0)
                {
                    oldDirName = dirname;
                    if (File.Exists(Path.Combine(dirname, "SonarLint.yescpp")))
                    {
                        logger.WriteLine("Accepting file in " + dirname + " due to SonarLint.yescpp . "+path);
                        break;
                    }

                    if (File.Exists(Path.Combine(dirname, "SonarLint.nocpp")))
                    {
                        logger.WriteLine("Ignoring  file in " + dirname + " due to SonarLint.nocpp . " + path);
                        return;
                    }

                    var sonarLintXml = Path.Combine(dirname, "SonarLint.xml");
                    if (File.Exists(sonarLintXml))
                    {
                        var content = File.ReadAllText(sonarLintXml);
                        if (content.Contains("SonarLintCppDisable"))
                        {
                            logger.WriteLine("Ignoring C,C++ file in " + dirname + " SonarLintCppDisable in SonarLint.xml : " +
                                             path);
                            return;
                        }
                        if (!content.Contains("SonarLintCppEnable"))
                        {
                            logger.WriteLine("Ignoring C,C++ file in " + dirname + " No SonarLintCppEnable in SonarLint.xml : " +
                                             path);
                            return;
                        }
                        break;
                    }

                    dirname = Path.GetFullPath(Path.Combine(dirname, ".."));
                    maxdepth--;
                }
            }
            catch (Exception)
            {
                // ignored
            }`
