### ISSUE TITLE
Synchronize C/C++ rules configuration in connected mode

### ISSUE THREAD

**Issue by duncanp-sonar** [SonarSource/sonarlint-visualstudio#1096]
### Description

Connected mode provides the following benefits:
(1) synchronises the set of rules being executed and configuration of those rules with the relevant Quality Profile on the connected server
(2)  does not report issues in the IDE that have been suppressed on the connected server

Supporting connected mode for C++ in SonarLint would simplify configuration, improve consistency and reduce noise in the IDE.

**NB this ticket only deals with point (1) above.**
#1107 deals with point (2)

#### Implementation overview
If the binding workflow detects that there is a C++ project in the solution then it will fetch the appropriate C++ Quality Profile during binding and save it locally.

When a subsequent CFamily analysis is triggered, the rules configuration and parameters from the QP will be used in the analysis.

Interaction with standalone rules configuration: the server-side QP configuration takes precedence over any standalone configuration i.e. any standalone configuration will be ignored. Log output should make this clear to the user.

Both SonarQube and SonarCloud projects will be supported.

#### Storage of rules configuration
The proposed solution is to store the rules configuration in a file in the `.sonarlint` folder. SLVS will check for the existence of the configuration file before calling the analyser.

This differs from how connected more works for C#/VB. There, the configuration (ruleset) is stored in the `.sonarlint` folder. However, the configuration is store in VS ruleset format. The MSBuild property '<CodeAnalysisRuleset>' is also set in each C#/VB project specifying which ruleset should be used. This is necessary in the case of C#/VB as VS/Roslyn is in charge of executing the analysis and it uses to the ruleset mechanism to decide which rules to execute.
The situation with CFamily analysis is different - we are entirely in control of the configuration and execution of the rules.

#### Telemetry
No new telemetry information will be recorded.

#### Tasks
- [x] #1099 - Fetch C++ rules configuration from the server (active rules and rule parameters)
- [x] #1100 - Modify rules configuration passed to `subprocess.exe` to use the server configuration
- [x] #1097 - Modify the binding workflow to allow C++ project types
- [x] #1098 - Modify the binding workflow to store C++ configuration in the `.sonarlint` folder
- [x] #1110 - Include CFamily QPs when checking if rules config is up to date
- [x] #1103 - Update user documentation

#### Related
Related:  [MMF-1877](https://jira.sonarsource.com/browse/MMF-1877) - Synchronize C/C++ rules configuration in connected mode
#770 - Support connected mode for JavaScript
#1107 -  Don't show resolved C/C++ issues in connected mode
