### ISSUE TITLE
Synchronize C/C++ issues in Connected Mode

### ISSUE THREAD

**Issue by duncanp-sonar** [SonarSource/sonarlint-visualstudio#1107]
### Description

Connected mode provides the following benefits:
(1) synchronises the set of rules being executed and configuration of those rules with the relevant Quality Profile on the connected server
(2) does not report issues in the IDE that have been suppressed on the connected server
(3) reports the issue-level severity set for each issue (i.e. if the user has changed the severity for a specific issue on the server)

Supporting connected mode for C++ in SonarLint would simplify configuration, improve consistency and reduce noise in the IDE.

**NB this ticket only deals with point (2) above.**
#1096 deals with point (1)

#### Implementation overview
TODO

Both SonarQube and SonarCloud projects will be supported.

#### Telemetry
No new telemetry information will be recorded.

#### Tasks
- [x] #1101 - Fetch suppressed CFamily issues from the server
- [x] #1268 - Implement suppression matching algorithm 
- [x] #1102 - Do not report issue if in suppression list
- [x] #1269 - Refresh suppression list in the background
- [x] #1287 - Updated wiki to document suppressions changes

#### Related
Related:  [MMF-1878](https://jira.sonarsource.com/browse/MMF-1878) - Don't show resolved C/C++ issues in connected mode
#770 - Support connected mode for JavaScript
#1096 - Synchronize C/C++ rules configuration in connected mode
