### ISSUE TITLE
Refactoring: create Core assembly without VS dependencies

### ISSUE THREAD

**Issue by duncanp-sonar** [SonarSource/sonarlint-visualstudio#1122]
### Description

The bulk of the SLVS code is in two projects, `Integration.csproj` and `Integration.Vsix.csproj`. Both of these have dependencies on VS. If there ever was any logical separation between the two assemblies it has been lost over time. This lack of logical separation makes it difficult to know where new classes should be added.
Both existing assemblies are also increasing in size and becoming more difficult to work with.

The code would be easier to understand and maintain if it the responsibilities of each project were clear. Some work has already been done to separate out related chunks of code e.g. creating the `Integration.TeamExplorer` project to contain VS-version specific TE code.

Creating a new Core project without VS assemblies will enable us to begin gradually refactoring the existing code base to improve the separation of concerns. For new features, the VS-independent code can be added directly to Core. Existing classes can be moved/refactored as they touched, time permitting.
It may make sense in future to create further separate projects for substantial features e.g. the CFamily analyzer integration, the daemon, or the connected mode logic.

### Tasks
- [x] create a new Core assembly that does not have dependencies on VS
- [x] move some of the existing VS-agnostic classes and interfaces into it e.g. `ILogger`
- [x] create a corresponding new test assembly and move the appropriate tests to it
- [x] check that the VSIX contains the new assembly
- [x] check that the new assembly is correctly signed and versioned
