### ISSUE TITLE
Investigate supporting the NodeJS based-version of SonarJS

### ISSUE THREAD

**Issue by duncanp-sonar** [SonarSource/sonarlint-visualstudio#1188]
### Description
The SonarJS plugin shipped in SLVS has not been updated for some time so users are not benefiting from the latest and greatest analysis rules.

However, the SonarJS plugin has changed so that it now requires NodeJS to run some of the rules (and more rules will be migrated from the Java to the NodeJS implementation going forward).

### TODO
* [ ] investigate whether NodeJS ships with VS: which version of NodeJS, which versions of VS
* [ ] if so, can we reliably locate the NodeJS used by VS?
* [ ] if not, can we install a version ourselves? (size, licensing, complexity etc)
* [ ] investigate the performance/UX impact of the new version of the plugin.

**Comment by bernieatwar** [comment]
What's the ETA for the support of the NodeJS Based version of SonarJS? My comment stems from #921. I have warnings show up on our Azure Pipelines Builds and would love to find a way around this. Thanks a lot
![azure-devops](https://user-images.githubusercontent.com/8920248/75392867-ece7d880-58ba-11ea-81b0-4a75e3f66376.PNG)

**Comment by duncanp-sonar** [comment]
@bernieatwar, changes in SonarLint won't have any impact on your Azure Pipeline builds.
The version of SonarJS used in the Azure build is the one from SonarQube/SonarCloud. If you are using SonarQube then you can upgrade the SonarJS plugin yourself (although make sure you read the release notes first since clearly the requirements for running the plugin have changed).

If you need more info, please open a thread in the [community forum](https://community.sonarsource.com/c/help/8).

**Comment by bernieatwar** [comment]
Ohhh indeed, very good point. I'll check it out. Thanks @duncanp-sonar!

**Comment by D66FA5A20AA8D4ADCF92051677C669962F72B4B** [comment]
For what it's worth, I believe since VS 2017 (perhaps earlier, too?), VS has shipped "external tools." I'm now running 2019, and the location of the external tools is located at `C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Web\External`.

These can be configured via Tools > Options:
![image](https://user-images.githubusercontent.com/60800049/75900236-daf5c080-5df9-11ea-81a5-7439bed88a0f.png)

My VS Version:
![image](https://user-images.githubusercontent.com/60800049/75900281-ee089080-5df9-11ea-8947-5a92eb79d43f.png)

My default set of packages (in .\node_modules\.bin):
- bower
- cake
- coffee
- coffeelint
- csslint
- grunt
- nopt
- rimraf
- strip-json-comments

Although I didn't see node or npm in there, there is a vs-task-server folder with a `npm-commands.js` file that appears to ensure npm is available and loaded.

**Comment by peter-dolkens** [comment]
VS will ship node only if it is selected in one of the installation packs.

If VS ships node, it installs a local copy, and loads it into the PATH of the running process from VSInstalledExternalTools

Importantly though - you can't *just* browse there - you need to obey the ordering of external web tools (which can be found under `Tools` > `Options`). This order is set in Windows Registry, though the exact location moves between versions, the rough location is:

`HKCU\Software\Microsoft\VisualStudio\14.0\ApplicationPrivateSettings\Microsoft\VisualStudio\Web\PackageManagement\ExternalTools\ExternalToolsOptionsPage`

Given all this, I suggest simply running `node -v` and parsing the result, then installing a portable version of node into a `.node` or similar folder should a copy not already exist.

You may also want to run `npm -v` and do the same.
