### ISSUE TITLE
Refresh suppression list in the background

### ISSUE THREAD

**Issue by duncanp-sonar** [SonarSource/sonarlint-visualstudio#1269]
### Description

The suppression list should be refreshed automatically in the background.

### TODO
- [x] the list should refresh when solution binding is updated, and periodically in the background (currently every 10 minutes)
- [x] reanalysis should be triggered when solution binding is updated
- [x] implement and test
