### ISSUE TITLE
Support reproducer for SLVS

### ISSUE THREAD

**Issue by abbas-sabra-sonarsource** [SonarSource/sonarlint-visualstudio#1295]
**Is your feature request related to a problem? Please describe.**
Currently, when subprocess fails on SLVS we have no way to debug why. 
When the `subprocess.exe` fails on SonarQube side, we automatically generate a reproducer file that can help us to debug the issue and fix it.
Also, the reproducer file can help if we want to regenerate what is happening on the user side. This would allow us to debug complex FP and performance bugs. 
**Describe the solution you'd like**
Add reproducer generation feature to SonarLint.

**Describe alternatives you've considered**
I don't think there is an alternative other than telling the user to try to regenerate the issue on SonarQube or SonarClound (if they already use them).

### Options
~~1) produce automatically in case of non-zero error code (i.e. crashes), and~~
2) user-triggered (to help diagnose FPs etc)
~3) always produce if logging level is detailed.~

### Implementation
Implement a new command in VS. The command won't be displayed on a menu. Instead, the user will invoke it from the Command Window with the code file open.

The command should:
* locate the active code window
* check it is a c/cpp file
* trigger an analysis with an extra flag to tell `subprocess.exe` to create the reproducer
* log any required information to the output window e.g. the location of the generated file.

The user will not be able to control the location to which the reproducer file is written.

TODO - decide whether to pop up a message box to tell the user where to find the reproducer as well as logging to the output window.

### TODO
- [x] change CFamily analyser so the caller can specify the reproducer should be run
- [x] add a menu command to trigger the analyser with reproducer
- [x] modify IAnalyzer to allow additional analyzer-specific properties to be passed
- [x] modify the analysis requestor to allow re-analysis of a single file
- [x] notify the user that the reproducer has been created and how to find it
- [x] unit tests
- [x] update wiki documentation

**Comment by rita-g-sonarsource** [comment]
@abbas-sabra-sonarsource what is the name of the flag?
