### ISSUE TITLE
Issues reported in the IDE should match those on the server

### ISSUE THREAD

**Issue by duncanp-sonar** [SonarSource/sonarlint-visualstudio#1336]
### Description
Developers using connected mode quite reasonably expect the issues reported in the IDE to match those in SonarQube/SonarCloud. However, there are multiple possible reasons why this is not currently the case. Some of these are bugs, some are technical restrictions, some are just work that hasn't been done yet.

This issue is an attempt to collect the various reasons for the client/server discrepancies, linking to specific actionable tickets where appropriate.

### Issues 
- [ ] #1335 server-side settings are not used by SLVS (e.g. inclusions/exclusions)

### Language-specific issues - C#/VB.NET
- [ ] project settings used by the Sonar Scanner for MSBuild are not used by SonarLint (i.e. `SonarQubeExclude` and `SonarQubeTestProject`). NOTE: these settings should also be respected in standalone mode.
- [ ] the logic used by the Sonar Scanner for MSBuild to classify test projects is different
- [ ] #176 - rules parameters are not synchronized
- [ ] #1005 - C#/VB suppressions mechanism is partially broken in VS2019 (and possible in later VS2017 updates)
* #632 - Quality Profiles are not applied to test projects

### Language-specific issues - JavaScript
- [ ] #770 - connnected mode is not implemented for JavaScript

**Comment by rantoniuk** [comment]
Another usecase:
- the project is scanning the repository using `sonar-scanner-cli` from the CI system
- the developers do not have permissions/do not want to create custom quality profiles be created in SQE so they rely on the default quality profile
- the project is disabling some false-positive rules via the sonar-project.properties file that is stored in the root of the project

The IDE could provide a setting or automatically detect a sonar-project.properties file present in the directory and use it to configure the ruleset used.

**Comment by KwazyCodi** [comment]
I am using Visual Studio Version 17.6.5 and connected to SonarCloud instance. I am not getting vulnerabilities and SonarLint logs says Found 0 issues. For same file in SonarCloud, I have SQL injection flagged. I have tired same on VS code, SonarLint is showing sql injection there.

**Comment by duncanp-sonar** [comment]
@KwazyCodi in VS, taint vulnerabilities are shown in a separate tool window. See [this wiki page](https://github.com/SonarSource/sonarlint-visualstudio/wiki/Security-Taint-Vulnerabilities-Investigation) for more information.

If you are still having problems please open a thread in the [community forum](https://community.sonarsource.com/c/sl/visual-studio/35).

**Comment by pavel-mikula-sonarsource** [comment]
Moved to [SLVS-2283](https://sonarsource.atlassian.net/browse/SLVS-2283)

[SLVS-2283]: https://sonarsource.atlassian.net/browse/SLVS-2283?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by HolisticDeveloper** [comment]
It appears that it will be much more difficult to follow any progress on issues that are moved over to Jira -- I tried to watch the new issue but received an error message ("We couldn't update your watch status.") ☹️
