### ISSUE TITLE
Delete redundant telemetry

### ISSUE THREAD

**Issue by duncanp-sonar** [SonarSource/sonarlint-visualstudio#1341]
### Description
The original telemetry was implemented by the team at Microsoft and sends data to Microsoft. SonarSource have no access to this data (and in the event it was not used by Microsoft either).
It should be removed.

Note: there is a second, completely independent telemetry implementation added by SonarSource that should be preserved.

### TODO
- [x] remove the code under `Integration.Vsix\Telemetry`
- [x] remove calls to the delete telemetry commands
- [x] CHECK that this has no impact on the loading of other features
- [x] remove corresponding tests
