### ISSUE TITLE
CFamily - use precompiled headers to speed up analysis

### ISSUE THREAD

**Issue by duncanp-sonar** [SonarSource/sonarlint-visualstudio#1557]
### Description

Relates to MMF-2079: https://jira.sonarsource.com/browse/MMF-2079

### TODO 

- [x] Update embedded CFamily analyzer and update the protocol to support the new parameters #1566
- [x] Implement file selection tracker that detects when a code file receives focus #1559
- [x] Trigger pre-analysis build when a code file is activated #1560
- [x] Pass PCH file location to the CFamily analyzer #1581
- [x] Implement PCH cache clean up strategy #1562

- ?logging
- ?telemetry
- ?documentation
