### ISSUE TITLE
Handle SQ open issue request

### ISSUE THREAD

**Issue by rita-g-sonarsource** [SonarSource/sonarlint-visualstudio#1798]
#### Description

Handle a request coming from SQ:

- [x] Verify that the request can be handled #1797
- [x] Fetch SQ hotspot #1771
~~- [ ] Fetch file hashes ?~~
~~- [ ] Fetch source code ? #1762~~
- [x] Convert SQ issue into IssueViz #1763
- [x] Push IssueViz into the hotspots data source #1795
- [x] Bring the hotspot list to front
