### ISSUE TITLE
Support TypeScript analysis

### ISSUE THREAD

**Issue by duncanp-sonar** [SonarSource/sonarlint-visualstudio#2181]
### Description

See [MMF-2287](https://jira.sonarsource.com/browse/MMF-2287)

#### TODO

- [ ] Provisioning: ?embed file uncompressed, embed compressed, download on demand?
- [ ] Support standalone rules configuration
- [ ] Add IAnalyzer implementation
- [ ] Update options page - ?separate options for JS/TS analysis?
- [ ] Update documentation

Notes:
* detection of Node, handling missing / incorrect node version
* initialization of Node server - not immediate -> delay/queue analysis requests during startup
* ?separate assembly for JS/TS?
* translation between Sxxx rule keys and ESLint rule keys
* ?separate Node instances for JS and TS, or a single instance?

To check:
* when to call init-linter: when the set of active rules changes?
* when to call new-tsconfig: when the file being analysed uses a different tsconfig file?
* eslintbridge::TSConfigFiles: is stateless, just called to resolve contents of tsconfig.json files?
* impact of `sonar-runtime`?
* eslintbridge `AnalysisRequest` type: has a property `List<String> tsConfigs;` ?only ever one value passed?
* are some external ESLint rules bundled as standard?

Potential changes on plugin side
* build and packaging: create a rule configuration file that includes both Sonar and ESLint rule keys
* runtime: ability to disable highlighting, cpd etc rules
