### ISSUE TITLE
Implement ESLint bridge wrapper

### ISSUE THREAD

**Issue by duncanp-sonar** [SonarSource/sonarlint-visualstudio#2184]
### Description

Implement wrapper class to launch and communicate with `eslintbridge`

#### TODO
- [ ] ~~Locate `eslintbridge` startup script~~ -> moved to #2256
- [x] Capture log and error output
- [x] Implement handlers for public `eslintbridge` methods
