### ISSUE TITLE
Implement TypeScript analyzer

### ISSUE THREAD

**Issue by duncanp-sonar** [SonarSource/sonarlint-visualstudio#2190]
### Description

Create implemention `IAnalyzer` that uses `eslintbridge`

#### TODO
- [x] ~~decide whether to implement separate JS and TS analyzers / separate `eslintbridge` instances~~ --> separate
- [x] ~~remove legacy analyzer implementation and tests~~ --> done in #2251 
- [x] ~~implement `eslintbridge` start-up. Analysis needs to be queued until `eslintbridge` is running.~~ --> done in #2184 
- [ ] fetch active rules. TODO - if the rules change, do we need to reset `eslintbridge`? YES.
- [ ] fetch appropriate `tsconfig` file
- [ ] if necessary, notify `eslintbridge` that a new `tsconfig` file is being used
- [ ] request analysis
- [ ] convert returned data to SLVS issues (see separate ticket for implementation rule key conversion)
- [ ] Use IAnalysisStatusNotifier for status reports
