### ISSUE TITLE
Implement rule key converter

### ISSUE THREAD

**Issue by duncanp-sonar** [SonarSource/sonarlint-visualstudio#2191]
### Description

There are two different sets of rule keys in use: the Sxxx rule keys used in SonarQube/SonarCloud, and the ESLint rule key.
Quality profiles will use the Sxxx for SonarSource rules.
The SonarJS plugin will contain a metadata file containing the mapping between Sxxx and ESLint rule keys.

#### TODO
- [x] decide whether to implement rule key translation in the first version - may not be required until Connected Mode is supported? UPDATE: the required metadata is in the file supplied with SonarJS, so implementing the mapping is simple.
- [x] check how bundled/external ESLint rules are handled - do they also have Sxxx numbers? UPDATE: not an issue; we'll use the metadata from the file
- [x] decide whether to include or strip the language prefix from the rule key e.g. `typescript:S123`. See below for screenshots from VS Code and IntelliJ, which do show the language. However, the layout is quite different from the VS Error List: DECISION - we'll start by stripping the repo prefix so the error code shown in the Error List in the same form as for other errors/warnings (including the SonarC# and SonarVB rules, and IDE/compiler error codes).
- [x] implement key mapper

#### VS Code
![image](https://user-images.githubusercontent.com/10757559/113830921-fb234c00-977e-11eb-91af-f81f28f0f571.png)

#### IntelliJ
![image](https://user-images.githubusercontent.com/10757559/113831228-49384f80-977f-11eb-8b08-33f4dc51bdd0.png)
