### ISSUE TITLE
Package the required eslint-bridge files

### ISSUE THREAD

**Issue by duncanp-sonar** [SonarSource/sonarlint-visualstudio#2246]
### Description

As part of the build, locate the additional files required for JavaScript/TypeScript analysis and package them in the SLVS vsix.

Note: this ticket follows on from #2182. The required files will be packaged in a new VSIX which will be added as an embedded dependency of the main SLVS VSIX. This approach avoids the build time "out of memory" error with the VSSDK tooling.

#### TODO
- [x] update `DownloadCFamilyPlugin` to handle fetching and unpacking the TypeScript plugin
- [x] rename `DownloadCFamilyPlugin` project, tasks, and referencing targets
- [x] add a new VSIX project to ship the required files
- [x] modify the SLVS VSIX manifests to embed the extra VSIX
- [x] check new process works on all dev and CI machines
- [x] manually test with VS2015, VS2017 and VS2019

Follows on from #2182
