### ISSUE TITLE
Add setting to disable all rules for a language

### ISSUE THREAD

**Issue by duncanp-lseg** [SonarSource/sonarlint-visualstudio#2340]
### Description

At present the only way to completely disable analysis for a language is to individually disable all of the rules for that language, either in the settings file (standalone mode) or in the Quality Profile (connected mode). This isn't a practical solution, given that each language has hundreds of rules.

It should be possible to disable all of the rules for a specific language via a single setting in the user settings file.

#### Out of scope
The following features are out of scope for now:
* UI to disable/enable languages

#### Should the setting apply in Connected mode, or only in Standalone mode?
At present, the rule configurations in the user settings file are ignored in Connected mode, the thinking being that the Quality Profile settings should take precedence in that case.

However, the individual developer should be in control of the development experience in their IDE, so they should be able to completely disable analysis for a language if they wish.

#### TODO
- [x] add appropriate settings to the `settings.json` config file
- [x] update the JavaScript rules provider to respect the new setting
- [ ] update the CFamily rules provider to respect the new setting
- [ ] add telemetry to record disabled languages
- [ ] update documentation

#### File format
The json format of the new setting will be as follows:
```
{
  "sonarlint.general": {
    "disabledLanguages": ["cpp", "c", "js"]
  },

  "sonarlint.rules": {
...
  }
}
```

The values stored will be the Sonar language keys i.e. cpp, c, js, ts etc.

**Comment by Bosch-Eli-Black** [comment]
@duncanp-sonar Has any of this feature already been shipped as part of the SonarLint VS extension? I'm looking to disable SonarLint for JS and TS files, e.g.

```
  "sonarlint.general": {
    "disabledLanguages": ["js", "ts"]
  },
```

Thanks! 🙂

**Comment by duncanp-sonar** [comment]
Hi @Bosch-Eli-Black. No, it's not shipped. We ran out of time to implement it in the sprint and it was cut. It's still on the backlog, but not currently prioritised.

cc @marco-comi-sonarsource for info.

**Comment by Bosch-Eli-Black** [comment]
@duncanp-sonar Okay, thanks 🙂

I don't think this is a priority for us, either. I was hoping to be able to temporarily disable JS warnings while I tested out the SonarLint extension, but long-term, we probably want to use connected mode and/or configure which JS errors we want to see, anyway.

**Comment by duncanp-sonar** [comment]
@Bosch-Eli-Black FYI JS/TS rule configuration is currently only supported in standalone mode. Support for connected mode is covered in #770.

**Comment by Bosch-Eli-Black** [comment]
@duncanp-sonar Yes, thanks; I was just looking to use this feature as a quick hack before we configured out JS projects to be in connected mode. Once we're in connected mode, I don't think we'll need it 🙂

**Comment by rjgotten** [comment]
@duncanp-sonar 

I would really, really, really, _REALLY_ appreciate having this feature delivered in light of Microsoft having utterly stuffed up something wrt TypeScript typings and their general support for Intellisense - to the point where they now triggers an ocean of warnings on typings in `/node_modules` folders that are part of regular old ASP.NET web projects; not JS or TS projects, and are in fact meant to be consumed by _totally_ different tooling - i.e. Webpack in my case.

Problems on that end can be temporarily worked around by creating a dummy `jsconfig.json` or `tsconfig.json` file and just instructing it to exclude _everything_ which gets Visual Studio's builds; real-time intellisense; and code analysis features to shut their pot hole about these non-problems. 

But when you open a JS or TS file for a quick edit, it's SonarLint which will _still_ kick in analysis and that triggers the built-in TypeScript Intellisense to start digging and: _boom!_ -- you're right back to square one with a 2000+ error log being puked out in your face.

**Comment by duncanp-sonar** [comment]
@rjgotten 

> But when you open a JS or TS file for a quick edit, it's SonarLint which will still kick in analysis and that triggers the built-in TypeScript Intellisense

The SonarLint analysis of JS/TS is run in an external process; it is not connected with TypeScript IntelliSense in any way.
Doesn't the TypeScript IntelliSense kick in whenever the file is opened anyway, regardless of whether SonarLint is installed or not?

**Comment by vanbang9710** [comment]
I use other extensions for some of the languages supported by Sonarlint so I would appreciate this settings

**Comment by matthewf-ucsd** [comment]
I'm in a situation where I want to edit a file I don't manage (and it would be awkward to reformat the entire project when I want to make single-line changes) - but SonarLint is throwing so many "errors" (such as complaining about tabs vs spaces) that I can't see any real problems that need to be resolved, so I want to be able to disable it for a given file or language in a project. My only option seems to be to disable the extension. So, I hope this can be taken out of the backlog.

**Comment by NWBArk** [comment]
Hi, any update on this? In our project we have a solution which is a mixture of C++ and C# projects and we have a separate analyzer for C#, so we only use SonarLint for C++ analysis, we are very appreciated if language specific toggle can be implemented.

**Comment by martinbabu** [comment]
+1

**Comment by pavel-mikula-sonarsource** [comment]
Moved to [SLVS-2254](https://sonarsource.atlassian.net/browse/SLVS-2254)

[SLVS-2254]: https://sonarsource.atlassian.net/browse/SLVS-2254?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
