### ISSUE TITLE
[TSConfig] Monitor changes in tsconfig files

### ISSUE THREAD

**Issue by duncanp-sonar** [SonarSource/sonarlint-visualstudio#2359]
### Description

Whenever a tsconfig file changes, we need to re-calculate the list of source files to which that tsconfig file applies.

#### TODO
- [ ] listen for changes to tsconfig files (which ones? just ones referenced in the project?)
- [ ] trigger update of source file -> tsconfig map
- [ ] decide how to handle new tsconfig files being created
- [ ] file renames?

**Comment by duncanp-sonar** [comment]
Obsolete. The JS/TS analyzer is/has changed how it handles .tsconfig files.
