### ISSUE TITLE
Pass required environment vars to subprocess

### ISSUE THREAD

**Issue by duncanp-sonar** [SonarSource/sonarlint-visualstudio#2546]
### Description
The new subprocess protocol expects certain environment variables to be set.

Unfortunately, the spec doesn't say which. Rather it says "run from the VS command line, or run VsDevCmd.bat first", which doesn't help if the subprocess is being triggered programmatically.

It's not clear how many environment variables are required. Currently, the subprocess only complains that INCLUDE is missing.

Depends on #2539

### TODO

- [ ] calculate the value of the INCLUDE setting
- [ ] pass the INCLUDE setting to the subprocess as an environment variable
- [ ] repeat for any other environment variables that are then reported as missing. UPDATE: INCLUDE seems to be the only required value
