### ISSUE TITLE
Add sonar-secrets license file

### ISSUE THREAD

**Issue by duncanp-sonar** [SonarSource/sonarlint-visualstudio#2707]
### Description

The preferred approach is to put the secrets component in a separate sub-folder with a specific license file i.e. same as for the CFamily component.

In implementation terms, this is quite different from the CFamily component, however: the secrets component is referenced as a NuGet package, and the binary is a .NET assembly that needs to be referenced from the other SLVS binaries i.e. there are (a) packaging and (b) runtime problems to overcome.

### TODO

- [ ] move the secrets assembly(ies) to a separate sub-folder in the VSIX
- [ ] add a license file with similar wording to the CFamily wordin
- [ ] check the binary can be loaded at runtime
