### ISSUE TITLE
Drop support for Visual Studio 2015

### ISSUE THREAD

**Issue by duncanp-sonar** [SonarSource/sonarlint-visualstudio#2714]
### Description

We will stop shipping new versions of SonarLint for Visual Studio 2015 once Visual Studio 2022 ships.

### TODO
- [x] update the Marketplace description
- [x] delete VS2015-specific files
- [x] update the build pipeline
- [x] update the release pipeline
