### ISSUE TITLE
Drop support for VS 2017

### ISSUE THREAD

**Issue by duncanp-sonar** [SonarSource/sonarlint-visualstudio#2882]
### Description

As per the [deprecation notice](https://marketplace.visualstudio.com/items?itemName=SonarSource.SonarLintforVisualStudio2017
) on the Visual Studio Marketplace, new releases of SLVS for VS2017 will not be shipped after 1st March 2022.

### TODO
- [x] Add git tag to the latest 2017 version
- [x] Delete Manifest
- [x] Target files remove 2017
- [x] Search for "#if 2017" or #if 2019 and check if it's still relevant
- [x] Release pipeline: disable 2017 step
- [x] Build pipeline: create new pipeline without 2017 matrix/parameter (+remove triggers from the old one)
- [x] [Github branch protection](https://docs.gearset.com/en/articles/2437757-managing-status-check-rules-in-github): update the pipeline name 
- [ ] check Marketing/PMMs are aware so they can remove VS2017 from the list of supported version on sonarlint.org
- [x] consider updating major version number to v6.0 (i.e. same approach as when dropping support of VS2015 - #2714)
