### ISSUE TITLE
Increase minimum supported VS2019 version to v16.3

### ISSUE THREAD

**Issue by duncanp-sonar** [SonarSource/sonarlint-visualstudio#2892]
### Description

Prevent SLVS v2019 from being installed on versions prior to VS2019.3.

#### TODO
- [ ] set the lower version bound in the VS2019 manifest file
- [ ] create a new VM with VS2019.3 Community edition for testing
- [ ] check the VSIX installs on VS2019.3
- [ ] check the VSIX does not install on VS2019 RTM

### Notes

The SLVS C# suppression fix requires the Roslyn `DiagnosticSuppressor` feature, which first shipped in VS2019.3.
Installing a VSIX with a diagnostic suppressor in VS2019RTM causes an `AD1000` to be reported to the user in the Error List:

![image](https://user-images.githubusercontent.com/10757559/155723904-01bc172d-ee64-44d0-b650-2ffb6e3d7b96.png)

**Number of affected users:** according to telemetry, less than one percent of SLVS VS2019 users will be affected.

VS2019.3 was [released](https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-v16.3#--visual-studio-2019-version-1630) in September 2019. Currently, Microsoft support [VS2019.11 or later](https://docs.microsoft.com/en-us/visualstudio/productinfo/vs-servicing#older-versions-of-visual-studio).
