### ISSUE TITLE
Investigate project-level suppressions

### ISSUE THREAD

**Issue by duncanp-sonar** [SonarSource/sonarlint-visualstudio#2923]
### Description

The existing code has special handling for project-level issues.
It isn't clear is this is still required for Roslyn issues.

### TODO
- [x] check whether we have Sonar rules that raise project-level issues. Update: yes: S3904, S3990, S3992 (only the first is in Sonar Way)
- [x] check how these issues are normally reported in VS. UPDATE: nothing special - just reported as usual, but with nothing in the "File" column.
- [x] check whether they are reported in SonarQube/SonarCloud and whether they can be suppressed. UPDATE: yes, and yes.
- [x] if they can be suppressed, check what data is returned from the server. Update: yes. See screen shot below.

![image](https://user-images.githubusercontent.com/10757559/158204209-d8815d86-3d4b-45e8-bc24-373d99175017.png)

Project-level issues doesn't have a file path, so we can't map them directly to an MSBuild project.

The "module key" isn't going to be much use since SonarQube/SonarCloud no longer support sub-modules. Previously, the module key would have been the MSBuild project GUID. Now, it is just the Sonar project key.

So, we have suppressions from the server, but we can't tell which MSBuild project they apply to. It might be case that the message of the issue contains the name of the assembly to which it relates. It seems risky to rely on this, though.
