### ISSUE TITLE
Report suppression state in the Error List for non-Roslyn issues

### ISSUE THREAD

**Issue by duncanp-sonar** [SonarSource/sonarlint-visualstudio#2951]
### Description

Visual Studio has a "Suppressions" column in the Error List with a filter that allows uses to choose whether or not they want to see suppression. SonarC# and SonarVB issues can be filtered in this way already.

We should be able to add the same functionality for other non-Roslyn based analysis rules.

### Notes
See the VS docs e.g. [here](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.shell.tablemanager.standardtablekeynames.suppressionstate?view=visualstudiosdk-2022).
Our `IssueSnapshot` class is asked for data for the `suppression` column, but we don't return `(false, null)` from the method.

### TODO
- [x] confirm we can support this feature for non-Roslyn languages
- [x] update the `IAnalysisIssueVisualization` interface to support suppression state
- [x] update the existing issue viz implementations
