### ISSUE TITLE
[Infra] Change release pipeline to get overview.md and manifest files from the repo

### ISSUE THREAD

**Issue by duncanp-sonar** [SonarSource/sonarlint-visualstudio#3250]
### Description

When we publish a new version of the extension, we upload an `overview.md` file which provides the content for the Overview tab on the [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=SonarSource.SonarLintforVisualStudio2022) page. Each extension version can have slightly different content.
The same applies to the json manifest files.

At present, the `.md` files are generated in the release pipeline (hard-coded content in an in-line PowerShell script that is written to disk).
It would be better if the `.md` files were in the repository - easier to manage and version, easier for the PMMs to edit directly.

### TODO
- [ ] check whether there is any variable content in the files i.e. variable/values taken from the build/release
- [ ] add the files to the repo
- [ ] change the release pipeline to upload the appropriate file when publishing
