### ISSUE TITLE
Support sonar-secrets in Connected Mode

### ISSUE THREAD

**Issue by duncanp-sonar** [SonarSource/sonarlint-visualstudio#3382]
### Description

`sonar-secrets` will be added to SQ LTS / SonarCloud. Once that has been done, we can add support for Connected Mode.

#### TODO
- [x] synchronize Quality Profiles
- [x] support server-server suppressed issues
- [x] support server-side exclusions/inclusions
- [x] disallow "disable rule" in Connected Mode
