### ISSUE TITLE
Handle rule-cross reference links

### ISSUE THREAD

**Issue by duncanp-sonar** [SonarSource/sonarlint-visualstudio#3626]
### Description

Rule descriptions can contain cross-references to other rules.
Cross-references are in the form `{rule:[full rule key]}

e.g. `{rule:c:S131}`

Cross-references should be rendered as hyperlinks. When a user clicks on the hyperlink, the reference rule should be navigated to.

Note: some of the cross-references might point to rules that are not executed in the IDE e.g. security rules. In that case, clicking on the link should navigate the appropriate rule at `rules.sonarsource.com`.

#### Example of rules with cross-references
* https://rules.sonarsource.com/javascript/RSPEC-1764 (and the equivalent [TypeScript rule](https://rules.sonarsource.com/typescript/RSPEC-1764))
* https://rules.sonarsource.com/javascript/RSPEC-1871 (and the equivalent [TypeScript rule](https://rules.sonarsource.com/typescript/RSPEC-1871))
* https://rules.sonarsource.com/cpp/RSPEC-131
* https://rules.sonarsource.com/cpp/RSPEC-109

#### Sub-tasks
- [x] #4011 Create rule cross-reference parser 
- [x] #4012 Render rule cross-references as hyperlinks
- [x] #4013 Handle click on cross-reference hyperlinks
