### ISSUE TITLE
[Infra] Update SDK version used for SLVS 2019

### ISSUE THREAD

**Issue by duncanp-sonar** [SonarSource/sonarlint-visualstudio#3790]
### Description

We are using `Microsoft.VisualStudio.Sdk v15.0.1` when building SLVS2019.
We should upgrade to use a v16 version of the NuGet package.

### TODO
- [ ] upgrade package reference
- [ ] add required package dependencies to the SLVS NuGet feed
- [ ] build and test on a VM with only VS2016.3 installed
