### ISSUE TITLE
Support educational descriptions for issues

### ISSUE THREAD

**Issue by ugras-ergun-sonarsource** [SonarSource/sonarlint-visualstudio#4078]
### Description 

Show rich rule descriptions in Rule Help Window in Visual Studio

### TODO

- [x] Show rich descriptions whenever the rule definition has it.
- [x] Fallback to the simple description if no rich description is available
- [x] Choose the correct context for the analyzed issue (Taint only)

### Out of Scope

- Context choosing for local issues. It's not supported for local analyzers we will handle it when they are supported, here are the relevant tickets
	- [Get Context From CFamily Analyzers ](https://github.com/SonarSource/sonarlint-visualstudio/issues/4025)
	- [Get Context From JS/TS Analyzers ](https://github.com/SonarSource/sonarlint-visualstudio/issues/4026)
	- [Get Context From Roslyn Analyzers ](https://github.com/SonarSource/sonarlint-visualstudio/issues/4027)
