### ISSUE TITLE
Release v7.0

### ISSUE THREAD

**Issue by duncanp-sonar** [SonarSource/sonarlint-visualstudio#4505]
#### TODO - specific to this release
- [x] Check SLVS binding migration
- [x] Check DotNet binding migration
- [x] Publish updated documentation
- [x] Check Tfvc links work
- [x] delete Mend projects with v6.17 (would have been "next" minor release, but we bumped the major version -> 6.17 does not exist. Should archive all except v6.16, v7.0 and v 7.1)

#### TODO - general
- [x] Check Mend
- [x] Check GitHub milestone
- [x] Check SonarCloud status
- [x] Final smoke test of release bits
- [x] Trigger the Release pipeline
- [x] Publish the Git release
- [x] End of sprint announcement
- [x] Archive the previous project Mend (shared drive is not currently accessible so uploaded to SonarLint/Mend_Archive_Temp/SLVS)
- [x] [Run the post-release pipeline](https://dev.azure.com/sonarsource/DotNetTeam%20Project/_build?definitionId=114) to update the version number
