### ISSUE TITLE
Support running C++ MISRA rules

### ISSUE THREAD

**Issue by georgii-borovinskikh-sonarsource** [SonarSource/sonarlint-visualstudio#4604]
### Description

Version v6.47 of the CFamily adds MISRA rules for C and C++ (see #4571). However, the metadata data for these rules is stored in separate files from the "normal" rules, so the MISRA rules are not recognised by SonarLint for Visual Studio and so are not executed.

Note: all of the MISRA rules are disabled by default.

In standalone mode end users will be able toexecute them by explicitly enabling a rule in the `settings.json` file.
The rules will be executed in Connected Mode by activating them in the project's Quality Profile (or by setting the Quality Profile to the built-in `Mission critical` Quality Profile).

### Notes
The MISRA23 rules are not added to the main list and quality profile in the plugin jar. They are placed in a separate folder with a separate rule list and QP (which includes normal rules as well).

#### TODO
 - [ ] update the CFamily preprocessor to extract the MISRA rule list and rule json files
 - [ ] amend the rule provider to return the MISRA rule ids
 
### TODO - testing - standalone mode
 - [ ] check rules can be enabled and executed
 - [ ] check rules can be disabled
 - [ ] check rule help is shown in the IDE

### TODO - testing - Connected Mode
 - [ ] check rules can be enabled in QPs
 - [ ] check rules cannot be disabled in the IDE
 - [ ] check rule help is shown in the IDE
