### ISSUE TITLE
Issues category should show type and severity defined in SonarQube

### ISSUE THREAD

**Issue by christophelevis** [SonarSource/sonarlint-visualstudio#884]
### Description

Issue category shows default rule type and severity regardless the project is bound on SonarQube. It should match the type and severity defined in SonarQube.

### Repro Steps

1. Bind a solution to SonarQube
2. Look at the rule type and severity of issues in the Errors List, in the category field.

### Expected behavior

When the project is bound to SonarQube, the type and severity displayed in the category should be:
1. the ones of the issue in SonarQube, when the issue is already present
2. the severity defined for the rule in the Quality Profile used for the project

Notes: see MS docs: https://docs.microsoft.com/en-us/visualstudio/code-quality/use-roslyn-analyzers?view=vs-2019#rule-severity

### Actual behavior

Issue category always shows the default rule type and severity.

### Notes
See additional comments in #808.

### Issue breakdown
There are a number of sub-issues:
- [x] [rule-level] C#/VB: [#808] Issues should use the severity specified in the Quality Profile
- [x] [rule-level] CFamily: [#1384] Issues should use the severity specified in the Quality Profile
- [ ] [rule-level] JavScript: [#1385] Issues should use the severity specified in the Quality Profile

* [issue-level] Issues should use the issue-level severity, if set
* [issue-level] Issues should use the issue-level category, if set

Related issue(s) for standalone mode:
- [x] #1386 _[CFamily] Issue severity reported in standalone mode should not always be Warning_

### Current situation
Currently the Error List looks like this:
![image](https://user-images.githubusercontent.com/10757559/80803297-c63f6a00-8ba9-11ea-8a72-a4c582c39a02.png)

The SS `severity` is mapped to VS `severity`.
SS `type` is mapped to VS `Category`, a text field that is not displayed by default.

#### Per-rule customisation
It appears that users can customise the the _severity_ pre-rule in a custom profile.
However, it does not appear that they can change the _type_.

#### Per-issue customisation
Users are able to change both _severity_ and _type_ per-issue.

#### How to map from the SS _severity_ to the VS _severity_
SS has 'Info', 'Minor', 'Major', 'Critical', 'Blocker'
VS has 'None', 'Hidden', 'Info', 'Warning', 'Error'
'None' means "disabled".
'Hidden' is used to improve the UX in the IDE. The issue won't appear in the Error List, but there will be a squiggly in the editor.

**Question:** how many SonarC#/VB rules used Hidden?

Proposed mapping:
* Info -> Info
* Minor -> Info
* Major -> Warning
* Critical -> Warning
* Blocker -> ??? Warning or Error?
We need to think about the UX if we are going to use `Error`. See #808 for some of the potential issues e.g. will it break local builds?

**Question:** how many SonarC#/VB rules used Critical?
**Question:** what impact does using level Error have in the IDE? (this might vary depending on whether the user is referencing the analyzers as VSIX packages or not, and in VS it is possible to set MSBuild properties to control whether VSIX analyzers are run for in-IDE builds)

### Setting the category
The category string is not configured in the ruleset file. Instead, it is a field on the Roslyn `DiagnosticDescriptor`.
Current implementation: when SonarC#/VB raises an issue it creates a diagnostic descriptor. The "Category" description is taken from a resource file embedded in the analyzer (for completeness, the resource file is generated as part of the `sonar-dotnet` using information from the RSPECs).

**Question:** can the Category be set dynamically at runtime when reporting an issue?
**Answer:** yes, but it's ugly - need to create copy of the diagnostic and diagnostic descriptor. There are a couple of localization gotchas, but we can probably work round them.
Also, because this is being set dynamically it will suffer from the same problems as with suppressions i.e. if the analysis is done out of process then we won't be able to suppress or change the category.

**Comment by christophelevis** [comment]
Relates to https://github.com/SonarSource/sonarlint-visualstudio/issues/808

**Comment by duncanp-sonar** [comment]
Closing this ticket. The only remaining item is https://github.com/SonarSource/sonarlint-visualstudio/issues/1385, so there's no need to have this "group" ticket.

**Comment by dishavirk** [comment]
Hi @duncanp-sonar, @christophelevis  ,

this issue is still not fixed for C# analysers, I'm using SonarLint for VS2017 and despite innumerous tries, the severity of the custom rules is still being set to Warning regardless of their severity in the Quality Profile on SonarQube.
Since this ticket is closed, I was presuming that the issue is fixed but it seems to be still open. As a part of my troubleshooting, I reinstalled the SonarLint plugin, tried fetching the custom rules for different projects but none worked. It's critical for our projects to have a fix for this as soon as possible.
Can you please advise here?

**Comment by duncanp-sonar** [comment]
Hi @dishavirk. Please don't post identical comments on multiple tickets. It's a poor practice.
I'll reply on #808.
