### ISSUE TITLE
Remove modal prompt to install additional languages

### ISSUE THREAD

**Issue by duncanp-sonar** [SonarSource/sonarlint-visualstudio#924]
After installing SLVS and restarting VS (or on starting VS if the `Prompt to activate additional languages on startup` is selected) the use is shown a modal dialogue asking if they want to download the files required to support analysing additional languages. This is jarring and unexpected for VS users.

#### TODO
- [x] Delete the dialogue code
- [x] Remove the `Prompt to activate additional languages on startup` option
- [x] Test the impact on removing this settings from existing settings i.e. shouldn't fail if reloading old settings that contain the option
- [x] Test behaviour on first install

#### Out-of-scope for this MMF
* a less intrusive prompt e.g. gold bar, toast.
