### ISSUE TITLE
Delay starting the daemon until a file needs to be analyzed

### ISSUE THREAD

**Issue by duncanp-sonar** [SonarSource/sonarlint-visualstudio#926]
The daemon starts automatically when VS is launched. This happens even before a solution is opened, and will be running even if there are never any files it can analyse.
Also, once the C++ analyzer is extracted from the daemon, the daemon will only analyse JavaScript files (unless and until we add analysis of more languages).

To reduce the load on the end-user's machine, we won't start the daemon until a file is opened that can be analysed by the daemon.

#### Implications
* the initial analysis for that first file will be slower because of the overhead in starting up the Java daemon. However, we've decided that this is acceptable as long as the initial analysis appears within a relatively short time e.g. five seconds.
* in many VS sessions the daemon will never start. TODO: consider impact on telemetry.

#### TODO
- [x] Review the initialization code in the SonarLintDaemonPackage - currently responsible for launching the daemon/UI on startup? Separate out the download code so newer daemon versions are downloaded but not started.
- [x] Review analysis trigger code - check whether this is async or not.
- [x] Check exception handling when daemon fails to start: (1) initial exception should be handled gracefully. (2) What do we do next time a file is opened - try to start the daemon again? UPDATE: exception during start is handled gracefully, but the current file won't be analyzed. An attempt is made to start the daemon when the file is saved again.

~~- [ ] Check the list of file types that need to be analysed (not just `.js`, there are other types like '.vue')~~
