### ISSUE TITLE
Improve daemon acquisition and startup UX

### ISSUE THREAD

**Issue by duncanp-sonar** [SonarSource/sonarlint-visualstudio#927]
Relates to [MMF-1771](https://jira.sonarsource.com/browse/MMF-1771).
Supercedes #900 `Simplify setup/installation of support for additional languages`

- [x] #924 Remove modal prompt to install additional languages
- [x] #925 Remove the non-modal dialogue showing download progress
- [x] #926 Delay starting the daemon until a file needs to be analyzed
