### ISSUE TITLE
Modify build to acquire and package the correct C++ analyzer exe

### ISSUE THREAD

**Issue by duncanp-sonar** [SonarSource/sonarlint-visualstudio#929]
#### Notes
We need to embed the following:
* the subprocess exe
* the json files specify which rules to run and the parameters for those rules
* ?a set of `.h` files? These files are only required for ObjectiveC analysis, so we should be able to avoid using them
* the following `.json` files: Sonar_way_profile.json, RulesList.json, and all of the XXX_params.json files

All of the above are embedded in the CFamily plugin jar, which is publicly available at https://binaries.sonarsource.com/CommercialDistribution/sonar-cfamily-plugin/.

The simplest solution will be to download the whole jar, unzip it, and extract the bits we need.
This would also mean that anyone forking this repo will still be able to build SLVS, even though the CFamily jar is commercially licensed. It also means that we don't need to worry about having to provide credentials in our internal builds to pull the bits from non-public locations.

To enable testing of intermediate builds, it would be useful if the download location and CFamily plugin version could be parameterised to allow developers to set them locally.

#### TODO
- [ ] modify the build to download the jar from https://binaries.sonarsource.com/CommercialDistribution/sonar-cfamily-plugin/
- [ ] package the jar and json files into the VSIX. Check the new VSIX size
- [ ] test on Azure Pipeline build
- [ ] check the increase in build time for PR/CI builds. If the build time increases too much then it might be necessary to skip the CFamily packaging step in PR builds.
