### ISSUE TITLE
[C++] Embed C++ analyzer directly in the vsix

### ISSUE THREAD

**Issue by duncanp-sonar** [SonarSource/sonarlint-visualstudio#932]
Relates to [MMF-1771](https://jira.sonarsource.com/browse/MMF-1771).

The C++ analysis is currently executed indirectly via the Java daemon. This complicates the setup experiences (separate download to support C++ and JS analysis because the Java runtime is large) 

#### Comparison of old and new architectures
![image](https://user-images.githubusercontent.com/10757559/61310364-118bb600-a7ec-11e9-896b-dc0cdebe11c8.png)

### Sub-tickets

- [x] #928 Implement the C++ analyzer protocol reader/writer
- [x] #947 Implement the CFamily MsvcDriver
- [x] #948 Load rules and active rules configuration from Json files
- [x] #929 Modify build to acquire and package the correct C++ analyzer exe
- [x] #955 Load rules metadata from the CFamily Json files
- [x] #930 Extract the C++ handler code from the Java daemon code
- [x] #931 Update the daemon-specific UI to remove references to C++
- [x] #958 Call subprocess.exe to execute CFamily analysis
- [x] #963 Update daemon to version without the CFamily plugin (v4.3.2.2521)
- [x] #965 Update CFamily helper to use caching rules loader
- [x] #969 Populate the default rule severity and category
