### ISSUE TITLE
Update telemetry to record language usage

### ISSUE THREAD

**Issue by duncanp-sonar** [SonarSource/sonarlint-visualstudio#933]
Relates to [MMF-1771](https://jira.sonarsource.com/browse/MMF-1771).
Supercedes #900 `Simplify setup/installation of support for additional languages`

#### TODO
- [ ] Amend the existing telemetry to record the types of file being analysed i.e. C++, C#, VB.NET. ?JS?
- [ ] ? is any additional telemetry required about adding/removing support for additional languages?
- [ ] Update the sample telemetry data shown to the user in the `Tools`, `Options` pane

**Comment by christophelevis** [comment]
Also relates to [MMF-1147](https://jira.sonarsource.com/browse/MMF-1147).
We might want to collect the same performance information than in other IDEs.
