### ISSUE TITLE
Update license terms for the VSIX

### ISSUE THREAD

**Issue by duncanp-sonar** [SonarSource/sonarlint-visualstudio#934]
The C-Family analyzer code is licensed under a different, commercial license from the rest of the open source code in the VSIX.

The license terms in the VSIX need to be updated appropriately.

#### TODO

- [x] check SonarLint is distributed under LGPL v3
- [x] ship the C-family analyzer in it's own directory called `lib`
- [x] add a license file to be next to C/C++ distribution which containing:
    1. a proper copyright to SonarSource
    2. the following sentence: "The C/C++ binary can be used as part of SonarLint, but can not be copied and/or distributed without the express permission of SonarSource SA."
- [ ] add third party license for subprocess.exe
